language: java
deploy:
  skip_cleanup: true
  provider: heroku
  app: spark-example-rodrigo-pacheco
  api_key:
    secure: uowkY/Yr2i8ztlQvoeHjl8aIraosARM8DLbPhH5ak0hMtKfQTC+KOOZFs/wYFTmgVC4n+QgWf6GVs6c7D/75jJu828Y2W/pxWKzcFbPYnNfh0C2H8CHzUzzKQODqSQDXbX4GwCpf5KEB/ISM9Tg6l++eSy152xEyiIroBLuVxjh+n1tandqAdZAoI2a+EwDKD0dvq8T2Q1VcuBMFGVk0oxm9zAq6Irgw38+sZFF0lIzhvcambB8e+gu5pVajBC7lvAVLS2lbTq82LMo8vnGA/jxXPmSKZ5SxHVCQ/rBWyBhAXcRoxXgwWOPrERSlfGV/sk5QFpnbpXgza3uT8UdZdTyRnJ9Vh1zQQX2lksuWF+UZE6rk/S+f2hwo5EbOQ0N9SoGe7G/E0KQeGXit6bj49FnVQmv6ng38eOMOIzgNwSdl8bTr8QGW8zi+1x6yQrC3QdjnaARi4B8jounKt9OEMw8Ma61Q+ijd3iG9SyVkm7hX9WhqFdN6CC2Y1js4GTBzJQi8wsOzojOSKM1H9oY9HJhnyWeoV/OuPesejv0E5wJUZqGTu+PES3lrl502AuKOX0yFoI0GSj8uzV3IEo6z2KcKtH+nwZ62pywfUpm+kTQ+P0TnDZyQ0Sb5qfiFMnfd7KBZIDx5mUB61xYYK73rZ8nVDexcQBPTYwWHgUb6394=
